# Generated by Django 5.0.3 on 2025-05-01 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Infor',
            fields=[
                ('map_infor_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_units', models.IntegerField()),
                ('area_of_one_unit', models.FloatField()),
                ('walkable_area', models.CharField(max_length=200)),
                ('router_number', models.IntegerField()),
                ('router_location', models.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trainee', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('training_time', models.TimeField(default='00:00:00')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('map_infor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='target_tracking.map_infor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfor',
            fields=[
                ('device_infor_id', models.AutoField(primary_key=True, serialize=False)),
                ('rssi1', models.FloatField()),
                ('rssi2', models.FloatField()),
                ('rssi3', models.FloatField()),
                ('rssi4', models.FloatField()),
                ('accx', models.FloatField()),
                ('accy', models.FloatField()),
                ('accz', models.FloatField()),
                ('magx', models.FloatField()),
                ('magy', models.FloatField()),
                ('magz', models.FloatField()),
                ('gyrox', models.FloatField()),
                ('gyroy', models.FloatField()),
                ('gyroz', models.FloatField()),
                ('eulerx', models.FloatField()),
                ('eulery', models.FloatField()),
                ('eulerz', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target_tracking.device')),
            ],
        ),
        migrations.CreateModel(
            name='Fires_Location',
            fields=[
                ('fires_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('fires_location', models.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('map_infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target_tracking.map_infor')),
            ],
        ),
        migrations.CreateModel(
            name='RSSI_for_Training',
            fields=[
                ('rssi_for_training_id', models.AutoField(primary_key=True, serialize=False)),
                ('rssi1', models.FloatField()),
                ('rssi2', models.FloatField()),
                ('rssi3', models.FloatField()),
                ('rssi4', models.FloatField()),
                ('location', models.IntegerField()),
                ('axis_x', models.FloatField()),
                ('axis_y', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('map_infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target_tracking.map_infor')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee_Location',
            fields=[
                ('trainee_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('axis_x', models.FloatField()),
                ('axis_y', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('map_infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target_tracking.map_infor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
