# Generated by Django 5.0.3 on 2025-05-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('target_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfor',
            name='device',
        ),
    ]
