# Generated by Django 5.0.3 on 2025-05-30 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_tracking', '0002_remove_deviceinfor_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fires_location',
            name='fires_location',
        ),
        migrations.AddField(
            model_name='fires_location',
            name='fires_axis_x',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fires_location',
            name='fires_axis_y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fires_location',
            name='fires_size',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fires_location',
            name='task_number',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
