# Generated by Django 5.0.3 on 2025-06-11 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_tracking', '0003_remove_fires_location_fires_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fires_Location',
            new_name='Fires_Information',
        ),
        migrations.CreateModel(
            name='Data_for_Training',
            fields=[
                ('rssi_for_training_id', models.AutoField(primary_key=True, serialize=False)),
                ('rssi1', models.FloatField()),
                ('rssi2', models.FloatField()),
                ('rssi3', models.FloatField()),
                ('rssi4', models.FloatField()),
                ('magy', models.FloatField()),
                ('magz', models.FloatField()),
                ('location', models.IntegerField()),
                ('axis_x', models.FloatField()),
                ('axis_y', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('map_infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target_tracking.map_infor')),
            ],
        ),
        migrations.DeleteModel(
            name='RSSI_for_Training',
        ),
    ]
